# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@stylistic/*"
          - "typescript-eslint"
          - "@typescript-eslint/*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
