# Site settings
title: 踢锡部落格
SEOTitle: 踢锡部落格 | TC Blog | TC的博客
header-img: img/home-bg.jpg
email: tautcony@gmail.com
description: "试着记录点东西 | 都是些有的没的"
keyword: "TautCony, @tautcony, TC的博客, TC Blog, 博客, 个人网站, 踢锡部落格"
url: "https://tautcony.xyz"                     # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

author:
  twitter: tautcony
  github:  tautcony

# SNS settings
RSS: false
# It should be set a proper icon from http://fontawesome.io/icons/ or use a word instead
SocialAccount: [
    {
        title: "github",
        href: "https://github.com/tautcony",
        icon: "fa-github",
        content: ""
    },
    {
        title: "twitter",
        href: "https://twitter.com/tautcony",
        icon: "fa-twitter",
        content: ""
    },
    {
        title: "steam",
        href: "https://steamcommunity.com/id/tautcony",
        icon: "fa-steam",
        content: ""
    }
]


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: 
    - less
    - ts
    - build
    - node_modules
    - js/pangu.js/node_modules
    - vendor
    - apps/material/templates
    - gulpfile.ts
    - package.json
    - README.md
    - LICENSE
anchorjs: true                          # if you want to customize anchor. check out `anchorjs.html`
MathJax: true
particle404: true                       # enable a particle effect 404 page


# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate, jekyll-sitemap]
#octopress-minify-html



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Comment settings
#disqus_username: tautcony-blog
#widgetpack_id: 8982
utteranc:
  repo: tautcony/tautcony.github.io
  issue-term: pathname
  theme: github-light


google-site-verification: "k_t-1fgBwmMc3UsE3yUU5zGQbRN2a0cl-HljKO2odqY"

# Analytics settings
# Baidu Analytics
##ba_track_id:
# Google Analytics 4
ga_measurement_id: 'G-D7DJK0DHRY'            # Format: G-XXXXXXXXXX



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "专业混吃等死"
sidebar-avatar: /img/avatar-tautcony.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 2              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "VCB-Studio",
        href: "https://vcb-s.com/"
    },
    {
        title: "Memo von EFS",
        href: "https://amefs.net/"
    },
    {
        title: "小马哥",
        href: "https://vigoss18.github.io/"
    },
    {
        title: "神北小毬",
        href: "https://npchk.info/"
    },
    {
        title: "钱叔叔",
        href: "https://blog.gloriousdays.pw/"
    },
    {
        title: "linkthis",
        href: "https://linkthis.me/"
    },
    {
        title: "はかせ",
        href: "https://bodayw.blogspot.com/"
    },
    {
        title: "Breakertt Blog",
        href: "https://breakertt.moe/"
    },
    {
        title: "spinmry's 实验室",
        href: "https://blog.spinmry.moe/"
    },
    {
        title: "沈聚聚",
        href: "https://canjuly.github.io"
    }
]


excerpt_separator: <!--more-->
incremental: false
